### ISSUE TITLE
billability of Events is not fully implemented

### ISSUE THREAD

**Issue by oswynb** [anchor/borel-core#14]
billableVerb is not fully fleshed out and billableStatus does not exist. Both of these should be adapated to using the config-based format once it has been implemented.

Additionally billableEvent should bre renamed to billablePoint and should be implemented along the lines of:

billablePoint mGroup p@PollsterPoint{} = billableStatus mGroup p
billablePoint mGroup p@EventPoint{} = billableStatus mGroup p && billableVerb mGroup p

**Comment by tranma** [comment]
not applicable in 0.16.0

migrated to part of 0.16.1
