### ISSUE TITLE
Acceptance and unit test

### ISSUE THREAD

**Issue by tranma** [anchor/borel-core#2]
The coverage currently stands at 0%

**Comment by fractalcat** [comment]
Indeed, tests are kinda important. In particular, unit tests for parsing would be very useful right now.

**Comment by tranma** [comment]
I promise there will be tests in ceilometer-common

**Comment by fractalcat** [comment]
\o/

**Comment by oswynb** [comment]
Using roundtrip-aeson for borel Result types/Metric types could help with testing as well as ensuring correctness.

**Comment by fractalcat** [comment]
@oswynb quite possibly yes.

**Comment by tranma** [comment]
don't know about Result, but Metric is a moot point, since we have prisms for encode/decode now. And some prism laws quickcheck.

**Comment by tranma** [comment]
now has some unit tests, acceptance testing is private
