### ISSUE TITLE
instance_ram and instance_vcpus are not being parsed correctly

### ISSUE THREAD

**Issue by oswynb** [anchor/borel-core#22]
Both these metrics are being interpreted as Simple instead of Compound points leading to incorrect output.

**Comment by tranma** [comment]
do you used to have an ceilometer encode/decode holy grail? what happened to it?

**Comment by oswynb** [comment]
Things have gotten out of date, vaultaire-collector-ceilometer is the reference at the moment

**Comment by tranma** [comment]
not applicable after milestone 0.16.0
